// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwbmwozanhxjwfdxezmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3Ym13b3phbmh4andmZHhlem16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODMyNDYsImV4cCI6MjA2MzE1OTI0Nn0.XhMBJRsqIEeGMJH8c7M_D654cK7e1xvGIPRuMuJq_t4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);